Actually fail build when tests fail

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -40,10 +40,12 @@ jobs:
 
       - name: Run tests and display failures
         run: |
-          ./gradlew test --no-daemon || true
-          for file in $(find build/test-results/test -name "*.xml"); do
-            grep -oP '(?<=<failure message=")[^"]*' "$file" | while read -r line; do
-              echo -e "\e[31m$line\e[0m"
+          ./gradlew test --no-daemon || echo "Tests failed"
+          if [[ -d build/test-results/test ]]; then
+            for file in $(find build/test-results/test -name "*.xml"); do
+              grep -oP '(?<=<failure message=")[^"]*' "$file" | while read -r line; do
+                echo -e "\e[31m$line\e[0m"
+              done
             done
-          done
+          fi
         continue-on-error: false
